- name: define php_conf_path
  set_fact:
    php_conf_path: "{{ __php_conf_path }}"
  when: php_conf_path is not defined

- name: configure php.ini
  lineinfile:
    dest: "{{ php_conf_path }}"
    regexp: "{{ item.regexp }}"
    line: "{{ item.line }}"
    state: present
  with_items:
    - regexp: "^max_execution_time.?=.+$"
      line: "max_execution_time = {{ max_execution_time }}"
    - regexp: "^memory_limit.?=.+$"
      line: "memory_limit = {{ memory_limit }}"
    - regexp: "^upload_max_filesize.?=.+$"
      line: "upload_max_filesize = {{ upload_max_filesize }}"
    - regexp: "^post_max_size.?=.+$"
      line: "post_max_size = {{ post_max_size }}"
    - regexp: '.*date\.timezone.?=.+$'
      line: "date.timezone = {{ timezone }}"
  notify: restart apache
