---
- name: include os specific variables
  include_vars: "{{ ansible_os_family }}-{{ ansible_distribution_major_version }}.yml"

- name: include php specific variables
  include_vars: "{{ php_version }}.yml"

- name: define php variables
  set_fact:
    php_packages: "{{ __php_packages | list }}"
    enable_repo: "{{ __enable_repo }}"

- name: define repo url for epel and webtatic
  set_fact:
    epel_repo: "{{ __epel_repo }}"
    webtatic_repo: "{{ __webtatic_repo }}"

# setup and install tasks
- include: install.yml

# configure tasks
- include: configure.yml
  notify: restart apache